version: '3.4'
services:
  # --------------------------
  # container swagger
  # --------------------------  
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "container_swagger"
    ports:
      - "8085:8080"
    environment:
      URL: ${url_swagger}
    deploy:
      resources:
        limits:
          cpus: ".50"
          memory: 512M  