apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/kong-net: "true"
    io.kompose.service: kong-migrations
  name: kong-migrations
spec:
  containers:
    - args:
        - kong
        - migrations
        - bootstrap
      env:
        - name: KONG_CASSANDRA_CONTACT_POINTS
          value: kong-database
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: kong-database
        - name: KONG_PG_PASSWORD
          value: kong
      image: kong
      name: kong-migrations
      resources: {}
  restartPolicy: OnFailure
status: {}
