version: '3.8'

services:

  icarus-db:
    image: mysql
    container_name: container_db
    restart: on-failure
    environment:
      - MYSQL_USER=${user_mysql}
      - MYSQL_PASSWORD=${pwd_mysql}
      - MYSQL_ROOT_PASSWORD=${pwd_mysql}
    ports:
      - 3306:3306
    networks:
      - icarus-network
    volumes:
      - icarus-db:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          memory: 512M

  gateway:
    image: k4im/gateway:${version}
    container_name: container_gateway
    restart: on-failure
    ports:
      - 5258:5258
    networks:
      - icarus-network
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          memory: 512M

  estoque:
    image: k4im/estoque:${version}
    container_name: container_estoque
    restart: on-failure
    environment:
      - DB_CONNECTION=${connection_string_estoque}
      - RABBIT_MQ_USER=${rabbit_user}
      - RABBIT_MQ_PWD=${rabbit_pwd}
    networks:
      - icarus-network
      - rabbitMQ-network
    depends_on:
      - icarus-db
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 512M

  projetos:
    image: k4im/projeto:${version}
    container_name: container_projetos
    restart: on-failure
    environment:
      - DB_CONNECTION=${connection_string_projetos}
      - RABBIT_MQ_USER=${rabbit_user}
      - RABBIT_MQ_PWD=${rabbit_pwd}
    networks:
      - icarus-network
      - rabbitMQ-network
    depends_on:
      - icarus-db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1G
        reservations:
          memory: 512M

  autenticacao:
    image: k4im/autenticacao:${version}
    container_name: container_auth
    restart: on-failure
    environment:
      - DB_CONNECTION=${connection_string_auth}
      - RABBIT_MQ_USER=${rabbit_user}
      - RABBIT_MQ_PWD=${rabbit_pwd}
    networks:
      - icarus-network
      - rabbitMQ-network
    depends_on:
      - icarus-db
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 2G
        reservations:
          memory: 512M

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: container_broker
    restart: on-failure
    environment:
    - RABBITMQ_DEFAULT_USER=${rabbit_user}
    - RABBITMQ_DEFAULT_PASS=${rabbit_pwd}
    hostname: broker
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - db-broker:/var/lib/rabbitmq
    networks:
      - rabbitMQ-network
    deploy:
      resources:
        limits:
          memory: 256M

# --------------------------
# Volume utilizados para banco de dados mysql
volumes:
  icarus-db:

# Network que serão utilizadas
# Será utilizado a network para o backend 
# e uma network external sendo para comunicação do rabbitMQ
networks:
  rabbitMQ-network:
    external: true
  icarus-network:
