apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: swagger-ui
  name: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: swagger-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/swagger-default: "true"
        io.kompose.service: swagger-ui
    spec:
      containers:
        - env:
            - name: URL
              value: https://k4im.github.io/json/api.json
          image: swaggerapi/swagger-ui
          name: container-swagger
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: "536870912"
      restartPolicy: Always
status: {}
