apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/kong-net: "true"
        io.kompose.service: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: admin
            - name: RABBITMQ_DEFAULT_USER
              value: admin
          image: rabbitmq:3-management-alpine
          name: container-broker
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            limits:
              memory: "268435456"
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: db-broker
      hostname: broker
      restartPolicy: Always
      volumes:
        - name: db-broker
          persistentVolumeClaim:
            claimName: db-broker
status: {}
