// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using autenticacao.service.Data;

#nullable disable

namespace autenticacao.service.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230526163601_PessoaTable")]
    partial class PessoaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("autenticacao.service.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("autenticacao.service.Models.Pessoa", b =>
                {
                    b.OwnsOne("shared.models.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("PessoaId")
                                .HasColumnType("int");

                            b1.Property<string>("Bairro")
                                .HasColumnType("longtext")
                                .HasColumnName("Bairro");

                            b1.Property<string>("Cep")
                                .HasColumnType("longtext")
                                .HasColumnName("Cep");

                            b1.Property<string>("Cidade")
                                .HasColumnType("longtext")
                                .HasColumnName("Cidade");

                            b1.Property<int>("Numero")
                                .HasColumnType("int")
                                .HasColumnName("NumeroEndereco");

                            b1.Property<string>("Rua")
                                .HasColumnType("longtext");

                            b1.HasKey("PessoaId");

                            b1.ToTable("Pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.OwnsOne("shared.models.ValueObjects.Nome", "Nome", b1 =>
                        {
                            b1.Property<int>("PessoaId")
                                .HasColumnType("int");

                            b1.Property<string>("PrimeiroNome")
                                .HasColumnType("longtext")
                                .HasColumnName("PrimeiroNome");

                            b1.Property<string>("SobreNome")
                                .HasColumnType("longtext")
                                .HasColumnName("SobreNome");

                            b1.HasKey("PessoaId");

                            b1.ToTable("Pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.OwnsOne("shared.models.ValueObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<int>("PessoaId")
                                .HasColumnType("int");

                            b1.Property<string>("CodigoDeArea")
                                .HasColumnType("longtext")
                                .HasColumnName("Area");

                            b1.Property<string>("CodigoPais")
                                .HasColumnType("longtext")
                                .HasColumnName("Pais");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("NumeroTelefone");

                            b1.HasKey("PessoaId");

                            b1.ToTable("Pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId");
                        });

                    b.Navigation("Endereco");

                    b.Navigation("Nome");

                    b.Navigation("Telefone");
                });
#pragma warning restore 612, 618
        }
    }
}
