version: '3.8'

services:
  # --------------------------
  # Servidor de bus
  # --------------------------  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: container_broker
    restart: on-failure
    environment:
    - RABBITMQ_DEFAULT_USER=${rabbit_user}
    - RABBITMQ_DEFAULT_PASS=${rabbit_pwd}
    hostname: broker
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - db-broker:/var/lib/rabbitmq
    networks:
      - rabbitMQ-network
    deploy:
      resources:
        limits:
          memory: 256M

# --------------------------
volumes:
  db-broker:
networks:
    rabbitMQ-network:
        external: true
